### PR TITLE
Update text_l_en.yml

### PR DESCRIPTION
**Pull request by jekov296**
RULE CHANGE KR->EN

### CODE REVIEW

**Review by jekov296 — COMMENTED** [review]
BEST OF THE BEST

**Review by fryti112 — APPROVED** [review]
goooooooooood

**Review by ABETAKANOBU — APPROVED** [review]

**Comment by geonwoo237** [comment]
good

**Comment by baewoojun** [comment]
good

**Comment by dojihun** [comment]
nice

**Comment by baewoojun** [comment]
good

**Review by baewoojun — COMMENTED** [review]
good

**Review by gyeonginkang — COMMENTED** [review]
good!!!

**Pull request merged**
